name: run java

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2
      
    - name: Configurar JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: 11
        distribution: 'temurin'

    - name: compile test
      run: |
        javac -d . src/br/calebe/ticketmachine/**/*.java
        if [ $? -ne 0 ]; 
          then
            echo "Failed to compile code"
            exit 1
        fi

    - name: junit
      run: wget https://repo1.maven.org/maven2/org/junit/platform/junit-platform-console-standalone/1.9.3/junit-platform-console-standalone-1.9.3.jar

    - name: execute test junit
      run: |
        java -cp junit-platform-console-standalone-1.9.3.jar org.junit.platform.console.ConsoleLauncher --scan-classpath
        test_exit_code=$?
        
        if [ $test_exit_code -eq 0 ]; 
          then
            echo "test sucess"
        else
            echo "test failed"
            exit 1
        fi
